package com.kayako.sdk.messenger.conversation.fields.team;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class TeamTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Team */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_fields_team_Team_getCreatedAt_000_58e0d8f75aa8f286() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            Team param_2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param_2, "title", param_1);
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "memberCount", null);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getCreatedAt();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_fields_team_Team_getId_000_a4e5eda732d172b3() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            Team param_2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param_2, "title", param_1);
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "memberCount", null);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getId();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_fields_team_Team_getMemberCount_000_6d54a7fa6e473b5() throws Throwable {
        Integer retval;
        {
            /* Arrange */
            String param_1 = "";
            Team param_2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param_2, "title", param_1);
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "memberCount", null);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getMemberCount();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_fields_team_Team_getTitle_000_89294066485dc6() throws Throwable {
        String retval;
        {
            /* Arrange */
            Team param_0 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param_0, "title", null);
            Reflector.setField(param_0, "updatedAt", null);
            Reflector.setField(param_0, "memberCount", null);
            Reflector.setField(param_0, "id", null);
            Reflector.setField(param_0, "createdAt", null);
            /* Act */
            retval = param_0.getTitle();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_fields_team_Team_getUpdatedAt_000_892ffe4d7a6b0103() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            Team param_2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param_2, "title", param_1);
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "memberCount", null);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getUpdatedAt();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
