package com.kayako.sdk.messenger.conversation.fields.team;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class TeamTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Team */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        Team instance;
        {
            /* Arrange */
            Long id = null;
            String title = null;
            Integer memberCount = null;
            Long createdAt = null;
            Long updatedAt = null;
            /* Act */
            /* Creating object to test constructor */
            instance = new Team(id, title, memberCount, createdAt, updatedAt);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getCreatedAt() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            Team param2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param2, "title", param1);
            Reflector.setField(param2, "updatedAt", null);
            Reflector.setField(param2, "memberCount", null);
            Reflector.setField(param2, "id", null);
            Reflector.setField(param2, "createdAt", null);
            /* Act */
            retval = param2.getCreatedAt();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getId() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            Team param2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param2, "title", param1);
            Reflector.setField(param2, "updatedAt", null);
            Reflector.setField(param2, "memberCount", null);
            Reflector.setField(param2, "id", null);
            Reflector.setField(param2, "createdAt", null);
            /* Act */
            retval = param2.getId();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }


    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getMemberCount() throws Throwable {
        Integer retval;
        {
            /* Arrange */
            String param1 = "";
            Team param2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param2, "title", param1);
            Reflector.setField(param2, "updatedAt", null);
            Reflector.setField(param2, "memberCount", null);
            Reflector.setField(param2, "id", null);
            Reflector.setField(param2, "createdAt", null);
            /* Act */
            retval = param2.getMemberCount();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getTitle() throws Throwable {
        String retval;
        {
            /* Arrange */
            Team param0 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param0, "title", null);
            Reflector.setField(param0, "updatedAt", null);
            Reflector.setField(param0, "memberCount", null);
            Reflector.setField(param0, "id", null);
            Reflector.setField(param0, "createdAt", null);
            /* Act */
            retval = param0.getTitle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getUpdatedAt() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            Team param2 = (Team) Reflector.getInstance("com.kayako.sdk.messenger.conversation.fields.team.Team");
            Reflector.setField(param2, "title", param1);
            Reflector.setField(param2, "updatedAt", null);
            Reflector.setField(param2, "memberCount", null);
            Reflector.setField(param2, "id", null);
            Reflector.setField(param2, "createdAt", null);
            /* Act */
            retval = param2.getUpdatedAt();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
}
