package com.kayako.sdk.messenger.conversation.fields.team;

import org.junit.Test;
import org.junit.rules.ExpectedException;

public class TeamParserTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: TeamParser */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
