package com.kayako.sdk.base.manager;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;

public class EmptyManager_1Test {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: EmptyManager_1 */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 77 branch to line 77
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 60 branch to line 60
     * conditional line 60 branch to line 64
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
