package com.kayako.sdk.base.manager;

import com.diffblue.deeptestutils.Reflector;
import com.kayako.sdk.base.callback.EmptyCallback;
import com.kayako.sdk.base.requester.Requester;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.lang.reflect.Constructor;

import static org.junit.Assert.assertNotNull;

public class EmptyManager_1Test {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: EmptyManager_1 */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        Object instance;
        {
            /* Arrange */
            EmptyManager arg1a = null;
            EmptyCallback arg2a = null;
            /* Act */
            /* Creating object to test constructor */
            Class<?> c = Reflector.forName("com.kayako.sdk.base.manager.EmptyManager$1");
            Constructor<?> ctor = c.getDeclaredConstructor(Reflector.forName("com.kayako.sdk.base.manager.EmptyManager"), Reflector.forName("com.kayako.sdk.base.callback.EmptyCallback"));
            ctor.setAccessible(true);
            instance = ctor.newInstance(arg1a, arg2a);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 77 branch to line 77
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 60 branch to line 60
   * conditional line 60 branch to line 64
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void comkayakosdkbasemanagerEmptyManagerinit() throws Throwable {
        EmptyManager instance;
        {
            /* Arrange */
            Requester requester = null;
            /* Act */
            /* Creating object to test constructor */
            instance = new EmptyManager(requester);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }
}
