package com.kayako.sdk.base.manager;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;

public class ItemManager_1Test {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: ItemManager_1 */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 94 branch to line 94
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_base_manager_ItemManager_access$000_000_43ef7f00b8215c53() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser retval;
        {
            /* Arrange */
            ItemManager param_0 = (ItemManager) Reflector.getInstance("com.kayako.sdk.base.manager.ItemManager");
            Reflector.setField(param_0, "parser", null);
            Reflector.setField(param_0, "requester", null);
            ItemManager x0 = param_0;
            /* Act */
            Class<?> c = Reflector.forName("com.kayako.sdk.base.manager.ItemManager");
            Method m = c.getDeclaredMethod("access$000", Reflector.forName("com.kayako.sdk.base.manager.ItemManager"));
            m.setAccessible(true);
            retval = (com.kayako.sdk.base.parser.ItemParser) m.invoke(null, x0);
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
