package com.kayako.sdk.helpcenter.articles;

import com.diffblue.deeptestutils.Reflector;
import com.kayako.sdk.helpcenter.section.Section;
import com.kayako.sdk.helpcenter.user.UserMinimal;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class ArticleTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Article */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void init() throws Throwable {
        Article instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new Article();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getAuthor() throws Throwable {
        UserMinimal retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Long param6 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param6, "value", 0L);
            Article param7 = new Article();
            param7.setLastPosted(null);
            param7.setLastUpdated(null);
            param7.setAuthor(null);
            param7.setSection(null);
            param7.setId(param6);
            param7.setTitle(param3);
            param7.setUuid(param5);
            param7.setContents(param1);
            /* Act */
            retval = param7.getAuthor();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getContents() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Article param4 = new Article();
            param4.setLastPosted(null);
            param4.setLastUpdated(null);
            param4.setAuthor(null);
            param4.setSection(null);
            param4.setId(null);
            param4.setTitle(param1);
            param4.setUuid(param3);
            param4.setContents(null);
            /* Act */
            retval = param4.getContents();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getId() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Article param6 = new Article();
            param6.setLastPosted(null);
            param6.setLastUpdated(null);
            param6.setAuthor(null);
            param6.setSection(null);
            param6.setId(null);
            param6.setTitle(param3);
            param6.setUuid(param5);
            param6.setContents(param1);
            /* Act */
            retval = param6.getId();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getLastPosted() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Long param6 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param6, "value", 0L);
            Article param7 = new Article();
            param7.setLastPosted(null);
            param7.setLastUpdated(null);
            param7.setAuthor(null);
            param7.setSection(null);
            param7.setId(param6);
            param7.setTitle(param3);
            param7.setUuid(param5);
            param7.setContents(param1);
            /* Act */
            retval = param7.getLastPosted();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getLastUpdated() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Article param6 = new Article();
            param6.setLastPosted(null);
            param6.setLastUpdated(null);
            param6.setAuthor(null);
            param6.setSection(null);
            param6.setId(null);
            param6.setTitle(param3);
            param6.setUuid(param5);
            param6.setContents(param1);
            /* Act */
            retval = param6.getLastUpdated();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getSection() throws Throwable {
        Section retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Article param6 = new Article();
            param6.setLastPosted(null);
            param6.setLastUpdated(null);
            param6.setAuthor(null);
            param6.setSection(null);
            param6.setId(null);
            param6.setTitle(param3);
            param6.setUuid(param5);
            param6.setContents(param1);
            /* Act */
            retval = param6.getSection();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getTitle() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Article param4 = new Article();
            param4.setLastPosted(null);
            param4.setLastUpdated(null);
            param4.setAuthor(null);
            param4.setSection(null);
            param4.setId(null);
            param4.setTitle(null);
            param4.setUuid(param3);
            param4.setContents(param1);
            /* Act */
            retval = param4.getTitle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getUuid() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Article param4 = new Article();
            param4.setLastPosted(null);
            param4.setLastUpdated(null);
            param4.setAuthor(null);
            param4.setSection(null);
            param4.setId(null);
            param4.setTitle(param3);
            param4.setUuid(null);
            param4.setContents(param1);
            /* Act */
            retval = param4.getUuid();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
