package com.kayako.sdk.helpcenter.articles;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class GetArticleRequesterTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetArticleRequester */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        GetArticleRequester instance;
        {
            /* Arrange */
            String helpCenterUrl = null;
            long articleId = 0L;
            /* Act */
            /* Creating object to test constructor */
            instance = new GetArticleRequester(helpCenterUrl, articleId);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }


    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getHeaders() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            GetArticleRequester param2 = (GetArticleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleRequester");
            Reflector.setField(param2, "mHelpCenterUrl", param1);
            Reflector.setField(param2, "mArticleId", 0L);
            /* Act */
            retval = param2.getHeaders();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getHelpCenterUrl() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetArticleRequester param0 = (GetArticleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleRequester");
            Reflector.setField(param0, "mHelpCenterUrl", null);
            Reflector.setField(param0, "mArticleId", 0L);
            /* Act */
            retval = param0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getQueryParameters() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            GetArticleRequester param2 = (GetArticleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleRequester");
            Reflector.setField(param2, "mHelpCenterUrl", param1);
            Reflector.setField(param2, "mArticleId", 0L);
            /* Act */
            retval = param2.getQueryParameters();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
}
