package com.kayako.sdk.helpcenter.articles;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetArticleListRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetArticleListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 28 branch to line 28
     * conditional line 29 branch to line 29
     * conditional line 30 branch to line 30
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleListRequester__init__000_3851a04f5a18e125() throws Throwable {
        GetArticleListRequester instance;
        {
            /* Arrange */
            String helpCenterUrl = null;
            long sectionId = 7L;
            int offset = -9;
            int limit = 0;
            /* Act */
            /* Creating object to test constructor */
            instance = new GetArticleListRequester(helpCenterUrl, sectionId, offset, limit);
            /* Assert side effects */
            Assert.assertEquals(7L, Reflector.getInstanceField(instance, "mSectionId"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleListRequester_getEndpointUrl_000_aed1254fd878725f() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            GetArticleListRequester param_2 = (GetArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleListRequester");
            Reflector.setField(param_2, "mQueryParams", null);
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            Reflector.setField(param_2, "mSectionId", 0L);
            /* Act */
            retval = param_2.getEndpointUrl();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("/api/v1/articles.json", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleListRequester_getHeaders_000_add3a6ab9bdba5c7() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetArticleListRequester param_2 = (GetArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleListRequester");
            Reflector.setField(param_2, "mQueryParams", null);
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            Reflector.setField(param_2, "mSectionId", 0L);
            /* Act */
            retval = param_2.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleListRequester_getHelpCenterUrl_000_122d3c37da3557dd() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetArticleListRequester param_0 = (GetArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleListRequester");
            Reflector.setField(param_0, "mQueryParams", null);
            Reflector.setField(param_0, "mHelpCenterUrl", null);
            Reflector.setField(param_0, "mSectionId", 0L);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleListRequester_getQueryParameters_000_e071be56ffc502dd() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetArticleListRequester param_2 = (GetArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleListRequester");
            Reflector.setField(param_2, "mQueryParams", null);
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            Reflector.setField(param_2, "mSectionId", 0L);
            /* Act */
            retval = param_2.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
