package com.kayako.sdk.helpcenter.articles;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetArticleRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetArticleRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleRequester_getHeaders_000_1da1e514b757c59d() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetArticleRequester param_2 = (GetArticleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleRequester");
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            Reflector.setField(param_2, "mArticleId", 0L);
            /* Act */
            retval = param_2.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleRequester_getHelpCenterUrl_000_90b3a4bb30a2bbf3() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetArticleRequester param_0 = (GetArticleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleRequester");
            Reflector.setField(param_0, "mHelpCenterUrl", null);
            Reflector.setField(param_0, "mArticleId", 0L);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_articles_GetArticleRequester_getQueryParameters_000_a504fe67a971a294() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetArticleRequester param_2 = (GetArticleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.articles.GetArticleRequester");
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            Reflector.setField(param_2, "mArticleId", 0L);
            /* Act */
            retval = param_2.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
