package com.kayako.sdk.base.requester;

import com.diffblue.deeptestutils.Reflector;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class CommonRequester_1Test {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: CommonRequester_1 */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 20 branch to line 20
     */
    @Test
    public void comkayakosdkbaserequesterCommonRequester$1clinit() throws Throwable {
        Object constructed;
        {
            /* Act */
            /* Using constructor to test static initializer */
            constructed = Reflector.getInstance("com.kayako.sdk.base.requester.CommonRequester$1");
            assertNotNull(constructed);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void comkayakosdkbaserequesterCommonRequesterinit() throws Throwable {
        CommonRequester instance;
        {
            /* Arrange */
            RequestProperty requester = null;
            /* Act */
            /* Creating object to test constructor */
            instance = new CommonRequester(requester);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }
}
