package com.kayako.sdk.base.requester;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class CommonRequester_1Test {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: CommonRequester_1 */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 20 branch to line 20
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
