package com.kayako.sdk.base.requester;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertNotNull;

public class ResponseTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Response */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        Response instance;
        {
            /* Arrange */
            int statusCode = 0;
            String body = null;
            /* Act */
            /* Creating object to test constructor */
            instance = new Response(statusCode, body);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }
}
