package com.kayako.sdk.messenger.rating;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetRatingListRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetRatingListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_GetRatingListRequester_getHeaders_000_fc98ff52ae1dfdb7() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            com.kayako.sdk.auth.FingerprintAuth param_0 = (com.kayako.sdk.auth.FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            Reflector.setField(param_0, "fingerprintId", null);
            String param_2 = "";
            GetRatingListRequester param_3 = (GetRatingListRequester) Reflector.getInstance("com.kayako.sdk.messenger.rating.GetRatingListRequester");
            Reflector.setField(param_3, "mFingerprintAuth", param_0);
            Reflector.setField(param_3, "mConversationId", 0L);
            Reflector.setField(param_3, "mHelpdeskUrl", param_2);
            /* Act */
            retval = param_3.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Fingerprint-ID", null);
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_GetRatingListRequester_getHelpCenterUrl_000_df2102f076f7b46() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetRatingListRequester param_0 = (GetRatingListRequester) Reflector.getInstance("com.kayako.sdk.messenger.rating.GetRatingListRequester");
            Reflector.setField(param_0, "mFingerprintAuth", null);
            Reflector.setField(param_0, "mConversationId", 0L);
            Reflector.setField(param_0, "mHelpdeskUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
