package com.kayako.sdk.messenger.rating;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class PostRatingBodyParamsTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: PostRatingBodyParams */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 27 branch to line 30
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 18 branch to line 21
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_PostRatingBodyParams_getComment_000_e4dbd656b1c983bf() throws Throwable {
        String retval;
        {
            /* Arrange */
            PostRatingBodyParams param_0 = (PostRatingBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.rating.PostRatingBodyParams");
            Reflector.setField(param_0, "comment", null);
            Reflector.setField(param_0, "score", null);
            /* Act */
            retval = param_0.getComment();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_PostRatingBodyParams_getScore_000_d61751aea393ef2e() throws Throwable {
        Object retval;
        {
            /* Arrange */
            String param_1 = "";
            PostRatingBodyParams param_2 = (PostRatingBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.rating.PostRatingBodyParams");
            Reflector.setField(param_2, "comment", param_1);
            Reflector.setField(param_2, "score", null);
            /* Act */
            retval = param_2.getScore();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
