package com.kayako.sdk.messenger.rating;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class PutRatingRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: PutRatingRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 33 branch to line 33
     * conditional line 34 branch to line 37
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 33 branch to line 33
     * conditional line 34 branch to line 35
     * conditional line 35 branch to line 35
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_PutRatingRequester_getBodyParameters_000_c4d353a6c46c2556() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            PutRatingRequester param_2 = (PutRatingRequester) Reflector.getInstance("com.kayako.sdk.messenger.rating.PutRatingRequester");
            Reflector.setField(param_2, "mRatingId", 0L);
            Reflector.setField(param_2, "mHelpdeskUrl", param_1);
            Reflector.setField(param_2, "mBodyParams", null);
            Reflector.setField(param_2, "mConversationId", 0L);
            Reflector.setField(param_2, "mFingerprintAuth", null);
            /* Act */
            retval = param_2.getBodyParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_PutRatingRequester_getHeaders_000_bf6093e429900874() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            com.kayako.sdk.auth.FingerprintAuth param_0 = (com.kayako.sdk.auth.FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            Reflector.setField(param_0, "fingerprintId", null);
            String param_2 = "";
            PutRatingRequester param_3 = (PutRatingRequester) Reflector.getInstance("com.kayako.sdk.messenger.rating.PutRatingRequester");
            Reflector.setField(param_3, "mRatingId", 0L);
            Reflector.setField(param_3, "mHelpdeskUrl", param_2);
            Reflector.setField(param_3, "mBodyParams", null);
            Reflector.setField(param_3, "mConversationId", 0L);
            Reflector.setField(param_3, "mFingerprintAuth", param_0);
            /* Act */
            retval = param_3.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Fingerprint-ID", null);
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_PutRatingRequester_getHelpCenterUrl_000_53c55800c5218b68() throws Throwable {
        String retval;
        {
            /* Arrange */
            PutRatingRequester param_0 = (PutRatingRequester) Reflector.getInstance("com.kayako.sdk.messenger.rating.PutRatingRequester");
            Reflector.setField(param_0, "mRatingId", 0L);
            Reflector.setField(param_0, "mHelpdeskUrl", null);
            Reflector.setField(param_0, "mBodyParams", null);
            Reflector.setField(param_0, "mConversationId", 0L);
            Reflector.setField(param_0, "mFingerprintAuth", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
