package com.kayako.sdk.messenger.rating;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class PutRatingBodyParamsTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: PutRatingBodyParams */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 10 branch to line 10
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 14 branch to line 14
     */
}
