package com.kayako.sdk.messenger.rating;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class Rating_SCORETest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Rating_SCORE */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_Rating_getComment_000_25b188a1b1bace46() throws Throwable {
        String retval;
        {
            /* Arrange */
            Rating param_0 = (Rating) Reflector.getInstance("com.kayako.sdk.messenger.rating.Rating");
            Reflector.setField(param_0, "updatedAt", null);
            Reflector.setField(param_0, "score", null);
            Reflector.setField(param_0, "comment", null);
            Reflector.setField(param_0, "id", null);
            Reflector.setField(param_0, "createdAt", null);
            /* Act */
            retval = param_0.getComment();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_Rating_getCreatedAt_000_b9afe863a3bebd82() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            Rating param_2 = (Rating) Reflector.getInstance("com.kayako.sdk.messenger.rating.Rating");
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "score", null);
            Reflector.setField(param_2, "comment", param_1);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getCreatedAt();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_Rating_getId_000_60b9e97aa219f72e() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            Rating param_2 = (Rating) Reflector.getInstance("com.kayako.sdk.messenger.rating.Rating");
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "score", null);
            Reflector.setField(param_2, "comment", param_1);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getId();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_Rating_getScore_000_e3e4b2beb6acbba6() throws Throwable {
        Object retval;
        {
            /* Arrange */
            String param_1 = "";
            Rating param_2 = (Rating) Reflector.getInstance("com.kayako.sdk.messenger.rating.Rating");
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "score", null);
            Reflector.setField(param_2, "comment", param_1);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getScore();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_rating_Rating_getUpdatedAt_000_f6c0276d3b1635f1() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            Rating param_2 = (Rating) Reflector.getInstance("com.kayako.sdk.messenger.rating.Rating");
            Reflector.setField(param_2, "updatedAt", null);
            Reflector.setField(param_2, "score", null);
            Reflector.setField(param_2, "comment", param_1);
            Reflector.setField(param_2, "id", null);
            Reflector.setField(param_2, "createdAt", null);
            /* Act */
            retval = param_2.getUpdatedAt();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
