package com.kayako.sdk.messenger.rating;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class RatingIncludeArgumentTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: RatingIncludeArgument */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 14 branch to line 14
     */
}
