package com.kayako.sdk.messenger.conversation;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetConversationListRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetConversationListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 29 branch to line 29
     * conditional line 30 branch to line 30
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_GetConversationListRequester_getEndpointUrl_000_23d5851e9debc317() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            GetConversationListRequester param_2 = (GetConversationListRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversation.GetConversationListRequester");
            Reflector.setField(param_2, "mQueryParameters", null);
            Reflector.setField(param_2, "mFingerprintAuth", null);
            Reflector.setField(param_2, "mHelpdeskUrl", param_1);
            /* Act */
            retval = param_2.getEndpointUrl();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("api/v1/conversations", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_GetConversationListRequester_getHeaders_000_5a0871e7c6ab93ed() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            com.kayako.sdk.auth.FingerprintAuth param_0 = (com.kayako.sdk.auth.FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            Reflector.setField(param_0, "fingerprintId", null);
            GetConversationListRequester param_1 = (GetConversationListRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversation.GetConversationListRequester");
            Reflector.setField(param_1, "mQueryParameters", null);
            Reflector.setField(param_1, "mFingerprintAuth", param_0);
            Reflector.setField(param_1, "mHelpdeskUrl", null);
            /* Act */
            retval = param_1.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Fingerprint-ID", null);
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_GetConversationListRequester_getHelpCenterUrl_000_d510ee2d36560880() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetConversationListRequester param_0 = (GetConversationListRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversation.GetConversationListRequester");
            Reflector.setField(param_0, "mQueryParameters", null);
            Reflector.setField(param_0, "mFingerprintAuth", null);
            Reflector.setField(param_0, "mHelpdeskUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_GetConversationListRequester_getQueryParameters_000_13131ec96f504ba6() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetConversationListRequester param_2 = (GetConversationListRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversation.GetConversationListRequester");
            Reflector.setField(param_2, "mQueryParameters", null);
            Reflector.setField(param_2, "mFingerprintAuth", null);
            Reflector.setField(param_2, "mHelpdeskUrl", param_1);
            /* Act */
            retval = param_2.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
