package com.kayako.sdk.messenger.conversation;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetConversationRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetConversationRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_GetConversationRequester_getHeaders_000_9a24779b197fa439() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            com.kayako.sdk.auth.FingerprintAuth param_0 = (com.kayako.sdk.auth.FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            Reflector.setField(param_0, "fingerprintId", null);
            String param_2 = "";
            GetConversationRequester param_3 = (GetConversationRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversation.GetConversationRequester");
            Reflector.setField(param_3, "mFingerprintAuth", param_0);
            Reflector.setField(param_3, "mConversationId", null);
            Reflector.setField(param_3, "mHelpdeskUrl", param_2);
            /* Act */
            retval = param_3.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Fingerprint-ID", null);
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_GetConversationRequester_getHelpCenterUrl_000_4b3f2bc0574ad8a4() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetConversationRequester param_0 = (GetConversationRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversation.GetConversationRequester");
            Reflector.setField(param_0, "mFingerprintAuth", null);
            Reflector.setField(param_0, "mConversationId", null);
            Reflector.setField(param_0, "mHelpdeskUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_GetConversationRequester_getQueryParameters_000_57bf38141d6a4e74() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetConversationRequester param_2 = (GetConversationRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversation.GetConversationRequester");
            Reflector.setField(param_2, "mFingerprintAuth", null);
            Reflector.setField(param_2, "mConversationId", null);
            Reflector.setField(param_2, "mHelpdeskUrl", param_1);
            /* Act */
            retval = param_2.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
