package com.kayako.sdk.messenger.conversation;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class PostConversationBodyParams_SourceTypeTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: PostConversationBodyParams_SourceType */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 30 branch to line 30
     * conditional line 30 branch to line 34
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 18 branch to line 18
     * conditional line 18 branch to line 22
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_PostConversationBodyParams_getClientId_000_699c35c5c26ce292() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "??????";
            String param_5 = "????";
            String param_7 = "";
            PostConversationBodyParams param_8 = (PostConversationBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.conversation.PostConversationBodyParams");
            Reflector.setField(param_8, "clientId", null);
            Reflector.setField(param_8, "source", null);
            Reflector.setField(param_8, "name", param_7);
            Reflector.setField(param_8, "email", param_5);
            Reflector.setField(param_8, "subject", param_3);
            Reflector.setField(param_8, "contents", param_1);
            /* Act */
            retval = param_8.getClientId();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_PostConversationBodyParams_getContents_000_2331a2ae89c13374() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            String param_7 = "";
            PostConversationBodyParams param_8 = (PostConversationBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.conversation.PostConversationBodyParams");
            Reflector.setField(param_8, "clientId", param_1);
            Reflector.setField(param_8, "source", null);
            Reflector.setField(param_8, "name", param_7);
            Reflector.setField(param_8, "email", param_5);
            Reflector.setField(param_8, "subject", param_3);
            Reflector.setField(param_8, "contents", null);
            /* Act */
            retval = param_8.getContents();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_PostConversationBodyParams_getEmail_000_5765d5b583fa44ac() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            String param_7 = "";
            PostConversationBodyParams param_8 = (PostConversationBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.conversation.PostConversationBodyParams");
            Reflector.setField(param_8, "clientId", param_1);
            Reflector.setField(param_8, "source", null);
            Reflector.setField(param_8, "name", param_7);
            Reflector.setField(param_8, "email", null);
            Reflector.setField(param_8, "subject", param_5);
            Reflector.setField(param_8, "contents", param_3);
            /* Act */
            retval = param_8.getEmail();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_PostConversationBodyParams_getName_000_262c430dd0e0e0bb() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            String param_7 = "";
            PostConversationBodyParams param_8 = (PostConversationBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.conversation.PostConversationBodyParams");
            Reflector.setField(param_8, "clientId", param_1);
            Reflector.setField(param_8, "source", null);
            Reflector.setField(param_8, "name", null);
            Reflector.setField(param_8, "email", param_7);
            Reflector.setField(param_8, "subject", param_5);
            Reflector.setField(param_8, "contents", param_3);
            /* Act */
            retval = param_8.getName();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_PostConversationBodyParams_getSource_000_33c6ba69783eb218() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            Object param_2 = Reflector.getInstance("com.kayako.sdk.messenger.conversation.PostConversationBodyParams$SourceType");
            Reflector.setField(param_2, "name", null);
            Reflector.setField(param_2, "ordinal", 0);
            String param_4 = "";
            String param_6 = "";
            String param_8 = "";
            String param_10 = "";
            PostConversationBodyParams param_11 = (PostConversationBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.conversation.PostConversationBodyParams");
            Reflector.setField(param_11, "clientId", param_1);
            Reflector.setField(param_11, "source", param_2);
            Reflector.setField(param_11, "name", param_10);
            Reflector.setField(param_11, "email", param_8);
            Reflector.setField(param_11, "subject", param_6);
            Reflector.setField(param_11, "contents", param_4);
            /* Act */
            retval = param_11.getSource();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversation_PostConversationBodyParams_getSubject_000_33c7febe81a52177() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "????";
            String param_7 = "";
            PostConversationBodyParams param_8 = (PostConversationBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.conversation.PostConversationBodyParams");
            Reflector.setField(param_8, "clientId", param_1);
            Reflector.setField(param_8, "source", null);
            Reflector.setField(param_8, "name", param_7);
            Reflector.setField(param_8, "email", param_5);
            Reflector.setField(param_8, "subject", null);
            Reflector.setField(param_8, "contents", param_3);
            /* Act */
            retval = param_8.getSubject();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
