package com.kayako.sdk.helpcenter.user;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertNotNull;

public class UserMinimalIncludeArgumentTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: UserMinimalIncludeArgument */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void clinit() throws Throwable {
        Object constructed;
        {
            /* Act */
            /* Using constructor to test static initializer */
            constructed = Reflector.getInstance("com.kayako.sdk.helpcenter.user.UserMinimalIncludeArgument");
            assertNotNull(constructed);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 16 branch to line 16
     */
    @Test
    public void init() throws Throwable {
        UserMinimalIncludeArgument instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new UserMinimalIncludeArgument();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }
}
