package com.kayako.sdk.helpcenter.user;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class UserMinimalIncludeArgumentTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: UserMinimalIncludeArgument */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 16 branch to line 16
     */
}
