package com.kayako.sdk.helpcenter.category;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class CategoryTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Category */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void init() throws Throwable {
        Category instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new Category();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getDescription() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            Category param2 = new Category();
            param2.setDescription(null);
            param2.setTitle(param1);
            param2.setDisplayOrder(null);
            param2.setId(null);
            /* Act */
            retval = param2.getDescription();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getDisplayOrder() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Category param4 = new Category();
            param4.setDescription(param1);
            param4.setTitle(param3);
            param4.setDisplayOrder(null);
            param4.setId(null);
            /* Act */
            retval = param4.getDisplayOrder();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getId() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Category param4 = new Category();
            param4.setDescription(param1);
            param4.setTitle(param3);
            param4.setDisplayOrder(null);
            param4.setId(null);
            /* Act */
            retval = param4.getId();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getTitle() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            Category param2 = new Category();
            param2.setDescription(param1);
            param2.setTitle(null);
            param2.setDisplayOrder(null);
            param2.setId(null);
            /* Act */
            retval = param2.getTitle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
