package com.kayako.sdk.helpcenter.category;

import com.diffblue.deeptestutils.Reflector;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class CategoryIncludeArgumentTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: CategoryIncludeArgument */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void clinit() throws Throwable {
        Object constructed;
        {
            /* Act */
            /* Using constructor to test static initializer */
            constructed = Reflector.getInstance("com.kayako.sdk.helpcenter.category.CategoryIncludeArgument");
            assertNotNull(constructed);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 18 branch to line 19
     * conditional line 19 branch to line 19
     */
    @Test
    public void init() throws Throwable {
        CategoryIncludeArgument instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new CategoryIncludeArgument();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }
}
