package com.kayako.sdk.helpcenter.category;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetCategoryListRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetCategoryListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 24 branch to line 24
     * conditional line 25 branch to line 25
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_category_GetCategoryListRequester_getEndpointUrl_000_9084c79ccda1dae8() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            GetCategoryListRequester param_2 = (GetCategoryListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.category.GetCategoryListRequester");
            Reflector.setField(param_2, "mHelpDeskUrl", param_1);
            Reflector.setField(param_2, "mQueryParams", null);
            /* Act */
            retval = param_2.getEndpointUrl();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("/api/v1/categories.json", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_category_GetCategoryListRequester_getHeaders_000_3d4c303703114e95() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetCategoryListRequester param_2 = (GetCategoryListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.category.GetCategoryListRequester");
            Reflector.setField(param_2, "mHelpDeskUrl", param_1);
            Reflector.setField(param_2, "mQueryParams", null);
            /* Act */
            retval = param_2.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_category_GetCategoryListRequester_getHelpCenterUrl_000_1917ebd17fda00cd() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetCategoryListRequester param_0 = (GetCategoryListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.category.GetCategoryListRequester");
            Reflector.setField(param_0, "mHelpDeskUrl", null);
            Reflector.setField(param_0, "mQueryParams", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_category_GetCategoryListRequester_getQueryParameters_000_d7c8e597929a01df() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetCategoryListRequester param_2 = (GetCategoryListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.category.GetCategoryListRequester");
            Reflector.setField(param_2, "mHelpDeskUrl", param_1);
            Reflector.setField(param_2, "mQueryParams", null);
            /* Act */
            retval = param_2.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
