package com.kayako.sdk.helpcenter.category;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class GetCategoryRequesterTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetCategoryRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void init() throws Throwable {
        GetCategoryRequester instance;
        {
            /* Arrange */
            String helpDeskUrl = null;
            long categoryId = 0L;
            /* Act */
            /* Creating object to test constructor */
            instance = new GetCategoryRequester(helpDeskUrl, categoryId);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getHeaders() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            GetCategoryRequester param2 = (GetCategoryRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.category.GetCategoryRequester");
            Reflector.setField(param2, "mCategoryId", 0L);
            Reflector.setField(param2, "mHelpDeskUrl", param1);
            /* Act */
            retval = param2.getHeaders();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getHelpCenterUrl() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetCategoryRequester param0 = (GetCategoryRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.category.GetCategoryRequester");
            Reflector.setField(param0, "mCategoryId", 0L);
            Reflector.setField(param0, "mHelpDeskUrl", null);
            /* Act */
            retval = param0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getQueryParameters() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            GetCategoryRequester param2 = (GetCategoryRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.category.GetCategoryRequester");
            Reflector.setField(param2, "mCategoryId", 0L);
            Reflector.setField(param2, "mHelpDeskUrl", param1);
            /* Act */
            retval = param2.getQueryParameters();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
}
