package com.kayako.sdk.helpcenter.section;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class GetSectionRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetSectionRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_GetSectionRequester_getHeaders_000_c643e04ba5d6f994() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetSectionRequester param_2 = (GetSectionRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.section.GetSectionRequester");
            Reflector.setField(param_2, "mSectionId", 0L);
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            /* Act */
            retval = param_2.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_GetSectionRequester_getHelpCenterUrl_000_d214b21a04fd6dff() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetSectionRequester param_0 = (GetSectionRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.section.GetSectionRequester");
            Reflector.setField(param_0, "mSectionId", 0L);
            Reflector.setField(param_0, "mHelpCenterUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
