package com.kayako.sdk.helpcenter.section;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class SectionTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Section */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_Section_getCategory_000_b79373a26d0869fb() throws Throwable {
        com.kayako.sdk.helpcenter.category.Category retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Section param_6 = (Section) Reflector.getInstance("com.kayako.sdk.helpcenter.section.Section");
            Reflector.setField(param_6, "display_order", null);
            Reflector.setField(param_6, "category", null);
            Reflector.setField(param_6, "id", null);
            Reflector.setField(param_6, "title", param_5);
            Reflector.setField(param_6, "visibility", param_1);
            Reflector.setField(param_6, "description", param_3);
            /* Act */
            retval = param_6.getCategory();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_Section_getDescription_000_596b587b8631766b() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Section param_4 = (Section) Reflector.getInstance("com.kayako.sdk.helpcenter.section.Section");
            Reflector.setField(param_4, "display_order", null);
            Reflector.setField(param_4, "category", null);
            Reflector.setField(param_4, "id", null);
            Reflector.setField(param_4, "title", param_3);
            Reflector.setField(param_4, "visibility", param_1);
            Reflector.setField(param_4, "description", null);
            /* Act */
            retval = param_4.getDescription();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_Section_getDisplay_order_000_38a329ab7e02655c() throws Throwable {
        Integer retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Section param_6 = (Section) Reflector.getInstance("com.kayako.sdk.helpcenter.section.Section");
            Reflector.setField(param_6, "display_order", null);
            Reflector.setField(param_6, "category", null);
            Reflector.setField(param_6, "id", null);
            Reflector.setField(param_6, "title", param_5);
            Reflector.setField(param_6, "visibility", param_1);
            Reflector.setField(param_6, "description", param_3);
            /* Act */
            retval = param_6.getDisplay_order();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_Section_getId_000_bb07a3a0eecc9ee1() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Section param_6 = (Section) Reflector.getInstance("com.kayako.sdk.helpcenter.section.Section");
            Reflector.setField(param_6, "display_order", null);
            Reflector.setField(param_6, "category", null);
            Reflector.setField(param_6, "id", null);
            Reflector.setField(param_6, "title", param_5);
            Reflector.setField(param_6, "visibility", param_1);
            Reflector.setField(param_6, "description", param_3);
            /* Act */
            retval = param_6.getId();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_Section_getTitle_000_ad2738b08280dc77() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Section param_4 = (Section) Reflector.getInstance("com.kayako.sdk.helpcenter.section.Section");
            Reflector.setField(param_4, "display_order", null);
            Reflector.setField(param_4, "category", null);
            Reflector.setField(param_4, "id", null);
            Reflector.setField(param_4, "title", null);
            Reflector.setField(param_4, "visibility", param_1);
            Reflector.setField(param_4, "description", param_3);
            /* Act */
            retval = param_4.getTitle();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_section_Section_getVisibility_000_fc2ed1be4079a322() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Section param_4 = (Section) Reflector.getInstance("com.kayako.sdk.helpcenter.section.Section");
            Reflector.setField(param_4, "display_order", null);
            Reflector.setField(param_4, "category", null);
            Reflector.setField(param_4, "id", null);
            Reflector.setField(param_4, "title", param_3);
            Reflector.setField(param_4, "visibility", null);
            Reflector.setField(param_4, "description", param_1);
            /* Act */
            retval = param_4.getVisibility();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
