package com.kayako.sdk.helpcenter.section;

import com.diffblue.deeptestutils.Reflector;
import com.kayako.sdk.helpcenter.category.Category;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class SectionTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Section */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        Section instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new Section();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getCategory() throws Throwable {
        Category retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Section param6 = new Section();
            Reflector.setField(param6, "display_order", null);
            Reflector.setField(param6, "category", null);
            Reflector.setField(param6, "id", null);
            Reflector.setField(param6, "title", param5);
            Reflector.setField(param6, "visibility", param1);
            Reflector.setField(param6, "description", param3);
            /* Act */
            retval = param6.getCategory();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getDescription() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Section param4 = new Section();
            Reflector.setField(param4, "display_order", null);
            Reflector.setField(param4, "category", null);
            Reflector.setField(param4, "id", null);
            Reflector.setField(param4, "title", param3);
            Reflector.setField(param4, "visibility", param1);
            Reflector.setField(param4, "description", null);
            /* Act */
            retval = param4.getDescription();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getDisplayorder() throws Throwable {
        Integer retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Section param6 = new Section();
            Reflector.setField(param6, "display_order", null);
            Reflector.setField(param6, "category", null);
            Reflector.setField(param6, "id", null);
            Reflector.setField(param6, "title", param5);
            Reflector.setField(param6, "visibility", param1);
            Reflector.setField(param6, "description", param3);
            /* Act */
            retval = param6.getDisplay_order();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getId() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "";
            Section param6 = new Section();
            Reflector.setField(param6, "display_order", null);
            Reflector.setField(param6, "category", null);
            Reflector.setField(param6, "id", null);
            Reflector.setField(param6, "title", param5);
            Reflector.setField(param6, "visibility", param1);
            Reflector.setField(param6, "description", param3);
            /* Act */
            retval = param6.getId();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }



    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getTitle() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Section param4 = new Section();
            Reflector.setField(param4, "display_order", null);
            Reflector.setField(param4, "category", null);
            Reflector.setField(param4, "id", null);
            Reflector.setField(param4, "title", null);
            Reflector.setField(param4, "visibility", param1);
            Reflector.setField(param4, "description", param3);
            /* Act */
            retval = param4.getTitle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getVisibility() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            Section param4 = new Section();
            Reflector.setField(param4, "display_order", null);
            Reflector.setField(param4, "category", null);
            Reflector.setField(param4, "id", null);
            Reflector.setField(param4, "title", param3);
            Reflector.setField(param4, "visibility", null);
            Reflector.setField(param4, "description", param1);
            /* Act */
            retval = param4.getVisibility();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
}
