package com.kayako.sdk.messenger.conversationstarter;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertNotNull;

public class ConversationStarterIncludeArgumentTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: ConversationStarterIncludeArgument */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void clinit() throws Throwable {
        Object constructed;
        {
            /* Act */
            /* Using constructor to test static initializer */
            constructed = Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.ConversationStarterIncludeArgument");
            assertNotNull(constructed);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 18 branch to line 19
   * conditional line 19 branch to line 19
   */
    @Test
    public void init() throws Throwable {
        ConversationStarterIncludeArgument instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new ConversationStarterIncludeArgument();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }
}
