package com.kayako.sdk.messenger.conversationstarter;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class ConversationStarterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: ConversationStarter */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_ConversationStarter_getAverageReplyTime_000_f9e83916df5130c1() throws Throwable {
        Double retval;
        {
            /* Arrange */
            String param_1 = "";
            ConversationStarter param_2 = (ConversationStarter) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.ConversationStarter");
            Reflector.setField(param_2, "averageReplyTime", null);
            Reflector.setField(param_2, "realtimeUrl", param_1);
            Reflector.setField(param_2, "lastActiveAgents", null);
            /* Act */
            retval = param_2.getAverageReplyTime();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_ConversationStarter_getLastActiveAgents_000_af655ec47ce30fea() throws Throwable {
        java.util.List<com.kayako.sdk.helpcenter.user.UserMinimal> retval;
        {
            /* Arrange */
            String param_1 = "";
            ConversationStarter param_2 = (ConversationStarter) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.ConversationStarter");
            Reflector.setField(param_2, "averageReplyTime", null);
            Reflector.setField(param_2, "realtimeUrl", param_1);
            Reflector.setField(param_2, "lastActiveAgents", null);
            /* Act */
            retval = param_2.getLastActiveAgents();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_ConversationStarter_getRealtimeUrl_000_a4016264402838bc() throws Throwable {
        String retval;
        {
            /* Arrange */
            ConversationStarter param_0 = (ConversationStarter) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.ConversationStarter");
            Reflector.setField(param_0, "averageReplyTime", null);
            Reflector.setField(param_0, "realtimeUrl", null);
            Reflector.setField(param_0, "lastActiveAgents", null);
            /* Act */
            retval = param_0.getRealtimeUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
