package com.kayako.sdk.messenger.conversationstarter;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetConversationStarterRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetConversationStarterRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_GetConversationStarterRequester_getEndpointUrl_000_fbdf8c2413812338() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            GetConversationStarterRequester param_2 = (GetConversationStarterRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.GetConversationStarterRequester");
            Reflector.setField(param_2, "mAuth", null);
            Reflector.setField(param_2, "mHelpdeskUrl", param_1);
            /* Act */
            retval = param_2.getEndpointUrl();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("api/v1/conversations/starter", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 57 branch to line 60
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_GetConversationStarterRequester_getHeaders_000_46b5760ed9345c28() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetConversationStarterRequester param_2 = (GetConversationStarterRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.GetConversationStarterRequester");
            Reflector.setField(param_2, "mAuth", null);
            Reflector.setField(param_2, "mHelpdeskUrl", param_1);
            /* Act */
            retval = param_2.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 57 branch to line 58
     * conditional line 58 branch to line 58
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_GetConversationStarterRequester_getHeaders_001_1ab8da3abe683901() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            com.kayako.sdk.auth.FingerprintAuth param_2 = (com.kayako.sdk.auth.FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            Reflector.setField(param_2, "fingerprintId", param_1);
            String param_4 = "";
            GetConversationStarterRequester param_5 = (GetConversationStarterRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.GetConversationStarterRequester");
            Reflector.setField(param_5, "mAuth", param_2);
            Reflector.setField(param_5, "mHelpdeskUrl", param_4);
            /* Act */
            retval = param_5.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Fingerprint-ID", "");
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_GetConversationStarterRequester_getHelpCenterUrl_000_3a2d01d54b9b7121() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetConversationStarterRequester param_0 = (GetConversationStarterRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.GetConversationStarterRequester");
            Reflector.setField(param_0, "mAuth", null);
            Reflector.setField(param_0, "mHelpdeskUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_conversationstarter_GetConversationStarterRequester_getQueryParameters_000_cf97bf2435fb1b01() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetConversationStarterRequester param_2 = (GetConversationStarterRequester) Reflector.getInstance("com.kayako.sdk.messenger.conversationstarter.GetConversationStarterRequester");
            Reflector.setField(param_2, "mAuth", null);
            Reflector.setField(param_2, "mHelpdeskUrl", param_1);
            /* Act */
            retval = param_2.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
