package com.kayako.sdk.messenger.conversation.fields.status;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class StatusIncludeArgumentTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: StatusIncludeArgument */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 17 branch to line 17
     */
}
