package com.kayako.sdk.messenger.conversation.fields.status;

import org.junit.Test;
import org.junit.rules.ExpectedException;

public class StatusParserTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: StatusParser */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
