package com.kayako.sdk;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class ParserFactoryTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: ParserFactory */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getArticleItemParser_000_b381546615d4dae7() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.helpcenter.articles.Article> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getArticleItemParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
            Assert.assertEquals(null, Reflector.getInstanceField(Reflector.getInstanceField(retval, "mParser"), "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getArticleListParser_000_f06a3f18f0cd8c6a() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.helpcenter.articles.Article> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getArticleListParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
            Assert.assertEquals(null, Reflector.getInstanceField(Reflector.getInstanceField(retval, "mParser"), "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getArticleParser_000_dc3bbed0d3114d56() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.helpcenter.articles.Article> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getArticleParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals(null, Reflector.getInstanceField(retval, "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getAttachmentParser_000_c3377112582b7876() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.attachment.Attachment> retval;
        {
            /* Act */
            retval = ParserFactory.getAttachmentParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getCategoryItemParser_000_9f90b6f4b3609f3() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.helpcenter.category.Category> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getCategoryItemParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
            Assert.assertEquals(null, Reflector.getInstanceField(Reflector.getInstanceField(retval, "mParser"), "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getCategoryListParser_000_c0b7cd645472b955() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.helpcenter.category.Category> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getCategoryListParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
            Assert.assertEquals(null, Reflector.getInstanceField(Reflector.getInstanceField(retval, "mParser"), "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getCategoryParser_000_bbde71f4750cfd78() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.helpcenter.category.Category> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getCategoryParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals(null, Reflector.getInstanceField(retval, "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getConversationItemParser_000_83342ed6837ad823() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.messenger.conversation.Conversation> retval;
        {
            /* Act */
            retval = ParserFactory.getConversationItemParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getConversationListParser_000_dc39a227369b624e() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.messenger.conversation.Conversation> retval;
        {
            /* Act */
            retval = ParserFactory.getConversationListParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getConversationParser_000_21d03d6a5c7a9e6a() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.conversation.Conversation> retval;
        {
            /* Act */
            retval = ParserFactory.getConversationParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getConversationStarterItemParser_000_d089443f4db3da71() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.messenger.conversationstarter.ConversationStarter> retval;
        {
            /* Act */
            retval = ParserFactory.getConversationStarterItemParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getConversationStarterParser_000_2ebe3657714da118() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.conversationstarter.ConversationStarter> retval;
        {
            /* Act */
            retval = ParserFactory.getConversationStarterParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getErrorListParser_000_54a0e5c1578d176b() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.error.response.Error> retval;
        {
            /* Act */
            retval = ParserFactory.getErrorListParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getErrorParser_000_3f34350658dd252c() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.error.response.Error> retval;
        {
            /* Act */
            retval = ParserFactory.getErrorParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getItemRatingParser_000_39eaf5c68b86e874() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.messenger.rating.Rating> retval;
        {
            /* Act */
            retval = ParserFactory.getItemRatingParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getLocaleItemParser_000_1c228015fe35f2a0() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.helpcenter.locale.Locale> retval;
        {
            /* Act */
            retval = ParserFactory.getLocaleItemParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getLocaleListParser_000_8106facff569d891() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.helpcenter.locale.Locale> retval;
        {
            /* Act */
            retval = ParserFactory.getLocaleListParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getLocaleParser_000_8ff615656e4a83ae() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.helpcenter.locale.Locale> retval;
        {
            /* Act */
            retval = ParserFactory.getLocaleParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getLogListParser_000_8a0591bd1850e5d9() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.error.response.Log> retval;
        {
            /* Act */
            retval = ParserFactory.getLogListParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getLogParser_000_c776ecb51abaee30() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.error.response.Log> retval;
        {
            /* Act */
            retval = ParserFactory.getLogParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getMessageItemParser_000_94f369589ef85eb() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.messenger.message.Message> retval;
        {
            /* Act */
            retval = ParserFactory.getMessageItemParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getMessageListParser_000_863f8375392521e0() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.messenger.message.Message> retval;
        {
            /* Act */
            retval = ParserFactory.getMessageListParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getMessageParser_000_d3a84a0bc348d6ee() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.message.Message> retval;
        {
            /* Act */
            retval = ParserFactory.getMessageParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getNotificationListParser_000_87f6da306b650282() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.error.response.Notification> retval;
        {
            /* Act */
            retval = ParserFactory.getNotificationListParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getNotificationParser_000_2f49312b4e1d837b() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.error.response.Notification> retval;
        {
            /* Act */
            retval = ParserFactory.getNotificationParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getPriorityParser_000_b06f293c0fc8ef8c() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.conversation.fields.priority.Priority> retval;
        {
            /* Act */
            retval = ParserFactory.getPriorityParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getRatingListParser_000_6a3f3ab51d2e4cf3() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.messenger.rating.Rating> retval;
        {
            /* Act */
            retval = ParserFactory.getRatingListParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getRatingParser_000_9a3b3e7244bfd082() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.rating.Rating> retval;
        {
            /* Act */
            retval = ParserFactory.getRatingParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getReadMarkerParser_000_d26acc6a57798ba8() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.conversation.fields.readmarker.ReadMarker> retval;
        {
            /* Act */
            retval = ParserFactory.getReadMarkerParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getSearchArticleListParser_000_b7326a259e7625e9() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.helpcenter.search.SearchArticle> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getSearchArticleListParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
            Assert.assertEquals(null, Reflector.getInstanceField(Reflector.getInstanceField(retval, "mParser"), "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getSearchArticleParser_000_4607c9027b454244() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.helpcenter.search.SearchArticle> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getSearchArticleParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals(null, Reflector.getInstanceField(retval, "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getSectionItemParser_000_7c07a6f916a6f20d() throws Throwable {
        com.kayako.sdk.base.parser.ItemParser<com.kayako.sdk.helpcenter.section.Section> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getSectionItemParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
            Assert.assertEquals(null, Reflector.getInstanceField(Reflector.getInstanceField(retval, "mParser"), "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getSectionListParser_000_cec96e2b0da156ce() throws Throwable {
        com.kayako.sdk.base.parser.ListParser<com.kayako.sdk.helpcenter.section.Section> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getSectionListParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(Reflector.getInstanceField(retval, "mParser"));
            Assert.assertEquals(null, Reflector.getInstanceField(Reflector.getInstanceField(retval, "mParser"), "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getSectionParser_000_7a0d7a9e9edec3dc() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.helpcenter.section.Section> retval;
        {
            /* Arrange */
            java.util.Locale locale = null;
            /* Act */
            retval = ParserFactory.getSectionParser(locale);
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals(null, Reflector.getInstanceField(retval, "mLocale"));
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getStatusParser_000_3395dfb84740864a() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.conversation.fields.status.Status> retval;
        {
            /* Act */
            retval = ParserFactory.getStatusParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getTeamParser_000_bffb33af580efb54() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.conversation.fields.team.Team> retval;
        {
            /* Act */
            retval = ParserFactory.getTeamParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getThumbnailParser_000_a8e5b416a6a97fe1() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.messenger.attachment.Thumbnail> retval;
        {
            /* Act */
            retval = ParserFactory.getThumbnailParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_ParserFactory_getUserMinimalParser_000_8345f156554a3751() throws Throwable {
        com.kayako.sdk.base.parser.Parser<com.kayako.sdk.helpcenter.user.UserMinimal> retval;
        {
            /* Act */
            retval = ParserFactory.getUserMinimalParser();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
        }
    }
}
