package com.kayako.sdk.error.response;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class NotificationTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Notification */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_error_response_Notification_getResponseMessageType_000_38dc1437cf9d7d79() throws Throwable {
        Type retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Notification param_4 = (Notification) Reflector.getInstance("com.kayako.sdk.error.response.Notification");
            param_4.sticky = null;
            ;
            param_4.message = param_1;
            ;
            param_4.type = param_3;
            ;
            /* Act */
            retval = param_4.getResponseMessageType();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertNotNull(((String) Reflector.getInstanceField(retval, "name")));
            Assert.assertEquals("NOTIFICATION", ((String) Reflector.getInstanceField(retval, "name")));
            Assert.assertEquals(1, Reflector.getInstanceField(retval, "ordinal"));
        }
    }
}
