package com.kayako.sdk.error.response;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class Type_1Test {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Type_1 */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * case 2 of switch on line 14
     */
    @Test
    public void com_kayako_sdk_error_response_Type_toString_000_eb97799445edb8c7() throws Throwable {
        String retval;
        {
            /* Arrange */
            Type param_0 = (Type) Reflector.getInstance("com.kayako.sdk.error.response.Type");
            Reflector.setField(param_0, "name", null);
            Reflector.setField(param_0, "ordinal", 1);
            /* Act */
            retval = param_0.toString();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("Notification", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * case 1 of switch on line 14
     */
    @Test
    public void com_kayako_sdk_error_response_Type_toString_001_ffc735deb0f4e1cf() throws Throwable {
        String retval;
        {
            /* Arrange */
            Type param_0 = (Type) Reflector.getInstance("com.kayako.sdk.error.response.Type");
            Reflector.setField(param_0, "name", null);
            Reflector.setField(param_0, "ordinal", 0);
            /* Act */
            retval = param_0.toString();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("Error", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * case 3 of switch on line 14
     */
    @Test
    public void com_kayako_sdk_error_response_Type_toString_002_762a01f86dcc72bd() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            Type param_2 = (Type) Reflector.getInstance("com.kayako.sdk.error.response.Type");
            Reflector.setField(param_2, "name", param_1);
            Reflector.setField(param_2, "ordinal", 2);
            /* Act */
            retval = param_2.toString();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("Log", retval);
        }
    }
}
