package com.kayako.sdk.messenger.attachment;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class AttachmentTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Attachment */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getCreatedAt_000_d4de7adb83c29731() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Long param_6 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param_6, "value", 0L);
            String param_8 = "";
            Attachment param_9 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_9, "thumbnails", null);
            Reflector.setField(param_9, "urlDownload", param_1);
            Reflector.setField(param_9, "url", param_3);
            Reflector.setField(param_9, "height", null);
            Reflector.setField(param_9, "createdAt", null);
            Reflector.setField(param_9, "id", null);
            Reflector.setField(param_9, "name", param_8);
            Reflector.setField(param_9, "width", param_6);
            Reflector.setField(param_9, "type", param_5);
            Reflector.setField(param_9, "size", null);
            /* Act */
            retval = param_9.getCreatedAt();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getHeight_000_d48269f5be883a44() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Long param_6 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param_6, "value", 0L);
            String param_8 = "";
            Attachment param_9 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_9, "thumbnails", null);
            Reflector.setField(param_9, "urlDownload", param_1);
            Reflector.setField(param_9, "url", param_3);
            Reflector.setField(param_9, "height", null);
            Reflector.setField(param_9, "createdAt", null);
            Reflector.setField(param_9, "id", null);
            Reflector.setField(param_9, "name", param_8);
            Reflector.setField(param_9, "width", param_6);
            Reflector.setField(param_9, "type", param_5);
            Reflector.setField(param_9, "size", null);
            /* Act */
            retval = param_9.getHeight();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getId_000_969bc18f7ec08779() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Long param_6 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param_6, "value", 0L);
            String param_8 = "";
            Attachment param_9 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_9, "thumbnails", null);
            Reflector.setField(param_9, "urlDownload", param_1);
            Reflector.setField(param_9, "url", param_3);
            Reflector.setField(param_9, "height", null);
            Reflector.setField(param_9, "createdAt", null);
            Reflector.setField(param_9, "id", null);
            Reflector.setField(param_9, "name", param_8);
            Reflector.setField(param_9, "width", param_6);
            Reflector.setField(param_9, "type", param_5);
            Reflector.setField(param_9, "size", null);
            /* Act */
            retval = param_9.getId();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getName_000_ca04fce25ef5f2b1() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Long param_6 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param_6, "value", 0L);
            Attachment param_7 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_7, "thumbnails", null);
            Reflector.setField(param_7, "urlDownload", param_1);
            Reflector.setField(param_7, "url", param_3);
            Reflector.setField(param_7, "height", null);
            Reflector.setField(param_7, "createdAt", null);
            Reflector.setField(param_7, "id", null);
            Reflector.setField(param_7, "name", null);
            Reflector.setField(param_7, "width", param_6);
            Reflector.setField(param_7, "type", param_5);
            Reflector.setField(param_7, "size", null);
            /* Act */
            retval = param_7.getName();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getSize_000_7e9de155cb8980a9() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            String param_7 = "";
            Attachment param_8 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_8, "thumbnails", null);
            Reflector.setField(param_8, "urlDownload", param_1);
            Reflector.setField(param_8, "url", param_3);
            Reflector.setField(param_8, "height", null);
            Reflector.setField(param_8, "createdAt", null);
            Reflector.setField(param_8, "id", null);
            Reflector.setField(param_8, "name", param_7);
            Reflector.setField(param_8, "width", null);
            Reflector.setField(param_8, "type", param_5);
            Reflector.setField(param_8, "size", null);
            /* Act */
            retval = param_8.getSize();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getThumbnails_000_4b6e31c47ce80cd5() throws Throwable {
        java.util.List<Thumbnail> retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Long param_6 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param_6, "value", 0L);
            String param_8 = "";
            Attachment param_9 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_9, "thumbnails", null);
            Reflector.setField(param_9, "urlDownload", param_1);
            Reflector.setField(param_9, "url", param_3);
            Reflector.setField(param_9, "height", null);
            Reflector.setField(param_9, "createdAt", null);
            Reflector.setField(param_9, "id", null);
            Reflector.setField(param_9, "name", param_8);
            Reflector.setField(param_9, "width", param_6);
            Reflector.setField(param_9, "type", param_5);
            Reflector.setField(param_9, "size", null);
            /* Act */
            retval = param_9.getThumbnails();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getType_000_93b74240130c5b81() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Long param_4 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param_4, "value", 0L);
            String param_6 = "";
            Attachment param_7 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_7, "thumbnails", null);
            Reflector.setField(param_7, "urlDownload", param_1);
            Reflector.setField(param_7, "url", param_3);
            Reflector.setField(param_7, "height", null);
            Reflector.setField(param_7, "createdAt", null);
            Reflector.setField(param_7, "id", null);
            Reflector.setField(param_7, "name", param_6);
            Reflector.setField(param_7, "width", param_4);
            Reflector.setField(param_7, "type", null);
            Reflector.setField(param_7, "size", null);
            /* Act */
            retval = param_7.getType();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getUrlDownload_000_f6de7a390a992598() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Attachment param_6 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_6, "thumbnails", null);
            Reflector.setField(param_6, "urlDownload", null);
            Reflector.setField(param_6, "url", param_1);
            Reflector.setField(param_6, "height", null);
            Reflector.setField(param_6, "createdAt", null);
            Reflector.setField(param_6, "id", null);
            Reflector.setField(param_6, "name", param_5);
            Reflector.setField(param_6, "width", null);
            Reflector.setField(param_6, "type", param_3);
            Reflector.setField(param_6, "size", null);
            /* Act */
            retval = param_6.getUrlDownload();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getUrl_000_6de8c69aec54a389() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Long param_4 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param_4, "value", 0L);
            String param_6 = "";
            Attachment param_7 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_7, "thumbnails", null);
            Reflector.setField(param_7, "urlDownload", param_1);
            Reflector.setField(param_7, "url", null);
            Reflector.setField(param_7, "height", null);
            Reflector.setField(param_7, "createdAt", null);
            Reflector.setField(param_7, "id", null);
            Reflector.setField(param_7, "name", param_6);
            Reflector.setField(param_7, "width", param_4);
            Reflector.setField(param_7, "type", param_3);
            Reflector.setField(param_7, "size", null);
            /* Act */
            retval = param_7.getUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Attachment_getWidth_000_9830bf9e47f5db7c() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            String param_7 = "";
            Attachment param_8 = (Attachment) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Attachment");
            Reflector.setField(param_8, "thumbnails", null);
            Reflector.setField(param_8, "urlDownload", param_1);
            Reflector.setField(param_8, "url", param_3);
            Reflector.setField(param_8, "height", null);
            Reflector.setField(param_8, "createdAt", null);
            Reflector.setField(param_8, "id", null);
            Reflector.setField(param_8, "name", param_7);
            Reflector.setField(param_8, "width", null);
            Reflector.setField(param_8, "type", param_5);
            Reflector.setField(param_8, "size", null);
            /* Act */
            retval = param_8.getWidth();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
