package com.kayako.sdk.messenger.attachment;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class ThumbnailTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: Thumbnail */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Thumbnail_getCreatedAt_000_f40409a6392f24b() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Thumbnail param_6 = (Thumbnail) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Thumbnail");
            Reflector.setField(param_6, "createdAt", null);
            Reflector.setField(param_6, "url", param_1);
            Reflector.setField(param_6, "name", param_5);
            Reflector.setField(param_6, "width", null);
            Reflector.setField(param_6, "type", param_3);
            Reflector.setField(param_6, "size", null);
            Reflector.setField(param_6, "height", null);
            /* Act */
            retval = param_6.getCreatedAt();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Thumbnail_getHeight_000_600debc215c4abcd() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Thumbnail param_6 = (Thumbnail) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Thumbnail");
            Reflector.setField(param_6, "createdAt", null);
            Reflector.setField(param_6, "url", param_1);
            Reflector.setField(param_6, "name", param_5);
            Reflector.setField(param_6, "width", null);
            Reflector.setField(param_6, "type", param_3);
            Reflector.setField(param_6, "size", null);
            Reflector.setField(param_6, "height", null);
            /* Act */
            retval = param_6.getHeight();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Thumbnail_getName_000_fcba0ac25591c12b() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Thumbnail param_4 = (Thumbnail) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Thumbnail");
            Reflector.setField(param_4, "createdAt", null);
            Reflector.setField(param_4, "url", param_1);
            Reflector.setField(param_4, "name", null);
            Reflector.setField(param_4, "width", null);
            Reflector.setField(param_4, "type", param_3);
            Reflector.setField(param_4, "size", null);
            Reflector.setField(param_4, "height", null);
            /* Act */
            retval = param_4.getName();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Thumbnail_getSize_000_d3edf67baeee0d33() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Thumbnail param_6 = (Thumbnail) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Thumbnail");
            Reflector.setField(param_6, "createdAt", null);
            Reflector.setField(param_6, "url", param_1);
            Reflector.setField(param_6, "name", param_5);
            Reflector.setField(param_6, "width", null);
            Reflector.setField(param_6, "type", param_3);
            Reflector.setField(param_6, "size", null);
            Reflector.setField(param_6, "height", null);
            /* Act */
            retval = param_6.getSize();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Thumbnail_getType_000_3c0bb4baea9c07f3() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Thumbnail param_4 = (Thumbnail) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Thumbnail");
            Reflector.setField(param_4, "createdAt", null);
            Reflector.setField(param_4, "url", param_1);
            Reflector.setField(param_4, "name", param_3);
            Reflector.setField(param_4, "width", null);
            Reflector.setField(param_4, "type", null);
            Reflector.setField(param_4, "size", null);
            Reflector.setField(param_4, "height", null);
            /* Act */
            retval = param_4.getType();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Thumbnail_getUrl_000_ad690de2432b3a4b() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            Thumbnail param_4 = (Thumbnail) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Thumbnail");
            Reflector.setField(param_4, "createdAt", null);
            Reflector.setField(param_4, "url", null);
            Reflector.setField(param_4, "name", param_3);
            Reflector.setField(param_4, "width", null);
            Reflector.setField(param_4, "type", param_1);
            Reflector.setField(param_4, "size", null);
            Reflector.setField(param_4, "height", null);
            /* Act */
            retval = param_4.getUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_attachment_Thumbnail_getWidth_000_2d2e4a498653765d() throws Throwable {
        Long retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "";
            Thumbnail param_6 = (Thumbnail) Reflector.getInstance("com.kayako.sdk.messenger.attachment.Thumbnail");
            Reflector.setField(param_6, "createdAt", null);
            Reflector.setField(param_6, "url", param_1);
            Reflector.setField(param_6, "name", param_5);
            Reflector.setField(param_6, "width", null);
            Reflector.setField(param_6, "type", param_3);
            Reflector.setField(param_6, "size", null);
            Reflector.setField(param_6, "height", null);
            /* Act */
            retval = param_6.getWidth();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
