package com.kayako.sdk.error;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class KayakoExceptionTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: KayakoException */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_error_KayakoException_getCode_000_aba640677f125d81() throws Throwable {
        ErrorCode retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            KayakoException param_4 = (KayakoException) Reflector.getInstance("com.kayako.sdk.error.KayakoException");
            Reflector.setField(param_4, "responseMessages", null);
            Reflector.setField(param_4, "code", null);
            Reflector.setField(param_4, "message", param_1);
            Reflector.setField(param_4, "detailMessage", param_3);
            Reflector.setField(param_4, "cause", null);
            Reflector.setField(param_4, "throwable", null);
            Reflector.setField(param_4, "stackTrace", null);
            Reflector.setField(param_4, "suppressedExceptions", null);
            /* Act */
            retval = param_4.getCode();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_error_KayakoException_getMessage_000_a920faa9696e8e44() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            KayakoException param_2 = (KayakoException) Reflector.getInstance("com.kayako.sdk.error.KayakoException");
            Reflector.setField(param_2, "responseMessages", null);
            Reflector.setField(param_2, "code", null);
            Reflector.setField(param_2, "message", null);
            Reflector.setField(param_2, "detailMessage", param_1);
            Reflector.setField(param_2, "cause", null);
            Reflector.setField(param_2, "throwable", null);
            Reflector.setField(param_2, "stackTrace", null);
            Reflector.setField(param_2, "suppressedExceptions", null);
            /* Act */
            retval = param_2.getMessage();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_error_KayakoException_getResponseMessages_000_a16d2c6f41e9a8eb() throws Throwable {
        ResponseMessages retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            KayakoException param_4 = (KayakoException) Reflector.getInstance("com.kayako.sdk.error.KayakoException");
            Reflector.setField(param_4, "responseMessages", null);
            Reflector.setField(param_4, "code", null);
            Reflector.setField(param_4, "message", param_1);
            Reflector.setField(param_4, "detailMessage", param_3);
            Reflector.setField(param_4, "cause", null);
            Reflector.setField(param_4, "throwable", null);
            Reflector.setField(param_4, "stackTrace", null);
            Reflector.setField(param_4, "suppressedExceptions", null);
            /* Act */
            retval = param_4.getResponseMessages();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_error_KayakoException_getThrowable_000_94c23154c5f0b7bb() throws Throwable {
        Throwable retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            KayakoException param_4 = (KayakoException) Reflector.getInstance("com.kayako.sdk.error.KayakoException");
            Reflector.setField(param_4, "responseMessages", null);
            Reflector.setField(param_4, "code", null);
            Reflector.setField(param_4, "message", param_1);
            Reflector.setField(param_4, "detailMessage", param_3);
            Reflector.setField(param_4, "cause", null);
            Reflector.setField(param_4, "throwable", null);
            Reflector.setField(param_4, "stackTrace", null);
            Reflector.setField(param_4, "suppressedExceptions", null);
            /* Act */
            retval = param_4.getThrowable();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
