package com.kayako.sdk.helpcenter.search;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class GetSearchArticleListRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetSearchArticleListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 33 branch to line 33
     * conditional line 34 branch to line 34
     * conditional line 35 branch to line 35
     * conditional line 36 branch to line 36
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_GetSearchArticleListRequester_getEndpointUrl_000_49f553c7053968f0() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            GetSearchArticleListRequester param_4 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param_4, "mQueryParameters", null);
            Reflector.setField(param_4, "mQuery", param_1);
            Reflector.setField(param_4, "mHelpCenterUrl", param_3);
            /* Act */
            retval = param_4.getEndpointUrl();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("/api/v1/helpcenter/search", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_GetSearchArticleListRequester_getHeaders_000_77fa5d713d8f436d() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            GetSearchArticleListRequester param_4 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param_4, "mQueryParameters", null);
            Reflector.setField(param_4, "mQuery", param_1);
            Reflector.setField(param_4, "mHelpCenterUrl", param_3);
            /* Act */
            retval = param_4.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_GetSearchArticleListRequester_getHelpCenterUrl_000_1fd2fac0518786b() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            GetSearchArticleListRequester param_2 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param_2, "mQueryParameters", null);
            Reflector.setField(param_2, "mQuery", param_1);
            Reflector.setField(param_2, "mHelpCenterUrl", null);
            /* Act */
            retval = param_2.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_GetSearchArticleListRequester_getQueryParameters_000_f7c727e76faceb8a() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            GetSearchArticleListRequester param_4 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param_4, "mQueryParameters", null);
            Reflector.setField(param_4, "mQuery", param_1);
            Reflector.setField(param_4, "mHelpCenterUrl", param_3);
            /* Act */
            retval = param_4.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
