package com.kayako.sdk.helpcenter.search;

import com.diffblue.deeptestutils.Reflector;
import java.lang.reflect.Constructor;
import java.util.Map;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetSearchArticleListRequesterTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetSearchArticleListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void init() throws Throwable {
        Object instance;
        {
            /* Act */
            /* Creating object to test constructor */
            Class<?> c = Reflector.forName("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Constructor<?> ctor = c.getDeclaredConstructor();
            ctor.setAccessible(true);
            instance = ctor.newInstance();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 33 branch to line 33
     * conditional line 34 branch to line 34
     * conditional line 35 branch to line 35
     * conditional line 36 branch to line 36
     */
    @Test
    public void init1() throws Throwable {
        GetSearchArticleListRequester instance;
        {
            /* Arrange */
            String param3 = "\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"";
            String helpCenterUrl = param3;
            String query = null;
            int offset = -5;
            int limit = 0;
            /* Act */
            /* Creating object to test constructor */
            instance = new GetSearchArticleListRequester(helpCenterUrl, query, offset, limit);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getEndpointUrl() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            GetSearchArticleListRequester param4 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param4, "mQueryParameters", null);
            Reflector.setField(param4, "mQuery", param1);
            Reflector.setField(param4, "mHelpCenterUrl", param3);
            /* Act */
            retval = param4.getEndpointUrl();
        }
        {
            /* Assert result */
            assertNotNull(retval);
            assertEquals("/api/v1/helpcenter/search", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getHeaders() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            GetSearchArticleListRequester param4 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param4, "mQueryParameters", null);
            Reflector.setField(param4, "mQuery", param1);
            Reflector.setField(param4, "mHelpCenterUrl", param3);
            /* Act */
            retval = param4.getHeaders();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getHelpCenterUrl() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            GetSearchArticleListRequester param2 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param2, "mQueryParameters", null);
            Reflector.setField(param2, "mQuery", param1);
            Reflector.setField(param2, "mHelpCenterUrl", null);
            /* Act */
            retval = param2.getHelpCenterUrl();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getQueryParameters() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            GetSearchArticleListRequester param4 = (GetSearchArticleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.search.GetSearchArticleListRequester");
            Reflector.setField(param4, "mQueryParameters", null);
            Reflector.setField(param4, "mQuery", param1);
            Reflector.setField(param4, "mHelpCenterUrl", param3);
            /* Act */
            retval = param4.getQueryParameters();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
}
