package com.kayako.sdk.helpcenter.search;

import com.diffblue.deeptestutils.Reflector;
import com.kayako.sdk.helpcenter.articles.Article;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class SearchArticleTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: SearchArticle */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void init() throws Throwable {
        SearchArticle instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new SearchArticle();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getCategoryName() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "?????????";
            SearchArticle param4 = new SearchArticle();
            param4.setOriginalArticle(null);
            param4.setSectionName(param1);
            param4.setCategoryName(null);
            param4.setTitle(param3);
            /* Act */
            retval = param4.getCategoryName();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getOriginalArticle() throws Throwable {
        Article retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "?????????";
            SearchArticle param6 = new SearchArticle();
            param6.setOriginalArticle(null);
            param6.setSectionName(param1);
            param6.setCategoryName(param3);
            param6.setTitle(param5);
            /* Act */
            retval = param6.getOriginalArticle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getSectionName() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "?????????";
            SearchArticle param4 = new SearchArticle();
            param4.setOriginalArticle(null);
            param4.setSectionName(null);
            param4.setCategoryName(param1);
            param4.setTitle(param3);
            /* Act */
            retval = param4.getSectionName();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getTitle() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            SearchArticle param4 = new SearchArticle();
            param4.setOriginalArticle(null);
            param4.setSectionName(param1);
            param4.setCategoryName(param3);
            param4.setTitle(null);
            /* Act */
            retval = param4.getTitle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
