package com.kayako.sdk.helpcenter.search;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class SearchArticleTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: SearchArticle */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_SearchArticle_getCategoryName_000_2a089cbd0a70a67d() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "?????????";
            SearchArticle param_4 = (SearchArticle) Reflector.getInstance("com.kayako.sdk.helpcenter.search.SearchArticle");
            Reflector.setField(param_4, "originalArticle", null);
            Reflector.setField(param_4, "sectionName", param_1);
            Reflector.setField(param_4, "categoryName", null);
            Reflector.setField(param_4, "title", param_3);
            /* Act */
            retval = param_4.getCategoryName();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_SearchArticle_getOriginalArticle_000_56e70eefd41cf8e7() throws Throwable {
        com.kayako.sdk.helpcenter.articles.Article retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            String param_5 = "?????????";
            SearchArticle param_6 = (SearchArticle) Reflector.getInstance("com.kayako.sdk.helpcenter.search.SearchArticle");
            Reflector.setField(param_6, "originalArticle", null);
            Reflector.setField(param_6, "sectionName", param_1);
            Reflector.setField(param_6, "categoryName", param_3);
            Reflector.setField(param_6, "title", param_5);
            /* Act */
            retval = param_6.getOriginalArticle();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_SearchArticle_getSectionName_000_dd86e20be60246b() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "?????????";
            SearchArticle param_4 = (SearchArticle) Reflector.getInstance("com.kayako.sdk.helpcenter.search.SearchArticle");
            Reflector.setField(param_4, "originalArticle", null);
            Reflector.setField(param_4, "sectionName", null);
            Reflector.setField(param_4, "categoryName", param_1);
            Reflector.setField(param_4, "title", param_3);
            /* Act */
            retval = param_4.getSectionName();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_search_SearchArticle_getTitle_000_fbf21adad39b3d8a() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            String param_3 = "";
            SearchArticle param_4 = (SearchArticle) Reflector.getInstance("com.kayako.sdk.helpcenter.search.SearchArticle");
            Reflector.setField(param_4, "originalArticle", null);
            Reflector.setField(param_4, "sectionName", param_1);
            Reflector.setField(param_4, "categoryName", param_3);
            Reflector.setField(param_4, "title", null);
            /* Act */
            retval = param_4.getTitle();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
