package com.kayako.sdk.helpcenter.search;

import com.diffblue.deeptestutils.Reflector;
import com.kayako.sdk.helpcenter.articles.Article;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class SearchArticleTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: SearchArticle */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        SearchArticle instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new SearchArticle();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getCategoryName() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "?????????";
            SearchArticle param4 = new SearchArticle();
            Reflector.setField(param4, "originalArticle", null);
            Reflector.setField(param4, "sectionName", param1);
            Reflector.setField(param4, "categoryName", null);
            Reflector.setField(param4, "title", param3);
            /* Act */
            retval = param4.getCategoryName();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getOriginalArticle() throws Throwable {
        Article retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            String param5 = "?????????";
            SearchArticle param6 = new SearchArticle();
            Reflector.setField(param6, "originalArticle", null);
            Reflector.setField(param6, "sectionName", param1);
            Reflector.setField(param6, "categoryName", param3);
            Reflector.setField(param6, "title", param5);
            /* Act */
            retval = param6.getOriginalArticle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getSectionName() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "?????????";
            SearchArticle param4 = new SearchArticle();
            Reflector.setField(param4, "originalArticle", null);
            Reflector.setField(param4, "sectionName", null);
            Reflector.setField(param4, "categoryName", param1);
            Reflector.setField(param4, "title", param3);
            /* Act */
            retval = param4.getSectionName();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getTitle() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param1 = "";
            String param3 = "";
            SearchArticle param4 = new SearchArticle();
            Reflector.setField(param4, "originalArticle", null);
            Reflector.setField(param4, "sectionName", param1);
            Reflector.setField(param4, "categoryName", param3);
            Reflector.setField(param4, "title", null);
            /* Act */
            retval = param4.getTitle();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
}
