package com.kayako.sdk.utils;

import org.junit.Test;
import org.junit.rules.ExpectedException;

public class FingerprintUtilsTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: FingerprintUtils */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
