package com.kayako.sdk.utils;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertNotNull;

public class LocaleUtilsTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: LocaleUtils */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        LocaleUtils instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new LocaleUtils();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
   * This test covers `String getLanguage(String)' block 2 (line 11)
   * This test covers `String getLanguage(String)' block 3 (line 11)
   * This test covers `String getLanguage(String)' block 4 (line 11)
   * This test covers `String getLanguage(String)' block 5 (line 11)
   * This test covers `String getLanguage(String)' block 6 (line 12)
   * This test covers `String getLanguage(String)' block 7 (line 12)
   * This test covers `String getLanguage(String)' block 8 (line 12)
   * This test covers `String getLanguage(String)' block 9 (line 12)
   * This test covers `String getLanguage(String)' block 11 (line 12)
   * This test covers `String getLanguage(String)' block 12 (line 13)
   */
    @Test
    public void getLanguage() throws Throwable {
        String retval;
        {
            /* Arrange */
            String localeCode = null;
            /* Act */
            thrown.expect(NullPointerException.class);
            retval = LocaleUtils.getLanguage(localeCode);
            assertNotNull(retval);
        /* Method return type is void, or not expected to return */
        }
    }
}
