package com.kayako.sdk.helpcenter.locale;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class GetLocaleRequesterTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetLocaleRequester */
    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void init() throws Throwable {
        GetLocaleRequester instance;
        {
            /* Arrange */
            String helpCenterUrl = null;
            long localeId = 0L;
            /* Act */
            /* Creating object to test constructor */
            instance = new GetLocaleRequester(helpCenterUrl, localeId);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getHeaders() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            GetLocaleRequester param2 = (GetLocaleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleRequester");
            Reflector.setField(param2, "mLocaleId", 0L);
            Reflector.setField(param2, "mHelpCenterUrl", param1);
            /* Act */
            retval = param2.getHeaders();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire function.
   */
    @Test
    public void getHelpCenterUrl() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetLocaleRequester param0 = (GetLocaleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleRequester");
            Reflector.setField(param0, "mLocaleId", 0L);
            Reflector.setField(param0, "mHelpCenterUrl", null);
            /* Act */
            retval = param0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }


}
