package com.kayako.sdk.helpcenter.locale;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetLocaleRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetLocaleRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_locale_GetLocaleRequester_getHeaders_000_182c0341d69600d8() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetLocaleRequester param_2 = (GetLocaleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleRequester");
            Reflector.setField(param_2, "mLocaleId", 0L);
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            /* Act */
            retval = param_2.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_locale_GetLocaleRequester_getHelpCenterUrl_000_cac6f0fd6db5f40b() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetLocaleRequester param_0 = (GetLocaleRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleRequester");
            Reflector.setField(param_0, "mLocaleId", 0L);
            Reflector.setField(param_0, "mHelpCenterUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
