package com.kayako.sdk.helpcenter.locale;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetLocaleListRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetLocaleListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_locale_GetLocaleListRequester_getEndpointUrl_000_841b41d22e0c521b() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            GetLocaleListRequester param_2 = (GetLocaleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleListRequester");
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            /* Act */
            retval = param_2.getEndpointUrl();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            Assert.assertEquals("/api/v1/locales.json", retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_locale_GetLocaleListRequester_getHeaders_000_8e3487ba6037de59() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetLocaleListRequester param_2 = (GetLocaleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleListRequester");
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            /* Act */
            retval = param_2.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_locale_GetLocaleListRequester_getHelpCenterUrl_000_fe89851ab0e4508c() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetLocaleListRequester param_0 = (GetLocaleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleListRequester");
            Reflector.setField(param_0, "mHelpCenterUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_helpcenter_locale_GetLocaleListRequester_getQueryParameters_000_8fdc3056dc1e95cf() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            GetLocaleListRequester param_2 = (GetLocaleListRequester) Reflector.getInstance("com.kayako.sdk.helpcenter.locale.GetLocaleListRequester");
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            /* Act */
            retval = param_2.getQueryParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
