package com.kayako.sdk.helpcenter.locale;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class LocaleIncludeArgumentTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: LocaleIncludeArgument */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 16 branch to line 16
     */
}
