package com.kayako.sdk.auth;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class SessionAuthTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: SessionAuth */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 34 branch to line 34
     * conditional line 35 branch to line 35
     */
    @Test
    public void com_kayako_sdk_auth_SessionAuth_getHeaders_000_74099d8ca16750b1() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            SessionAuth param_0 = (SessionAuth) Reflector.getInstance("com.kayako.sdk.auth.SessionAuth");
            Reflector.setField(param_0, "userAgent", null);
            Reflector.setField(param_0, "sessionId", null);
            /* Act */
            retval = param_0.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Session-ID", null);
            hashMap.put("User-Agent", null);
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_auth_SessionAuth_getSessionId_000_b9fb0c199b8ac4de() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            SessionAuth param_2 = (SessionAuth) Reflector.getInstance("com.kayako.sdk.auth.SessionAuth");
            Reflector.setField(param_2, "userAgent", param_1);
            Reflector.setField(param_2, "sessionId", null);
            /* Act */
            retval = param_2.getSessionId();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_auth_SessionAuth_getUserAgent_000_15a8e502eb904e93() throws Throwable {
        String retval;
        {
            /* Arrange */
            String param_1 = "";
            SessionAuth param_2 = (SessionAuth) Reflector.getInstance("com.kayako.sdk.auth.SessionAuth");
            Reflector.setField(param_2, "userAgent", null);
            Reflector.setField(param_2, "sessionId", param_1);
            /* Act */
            retval = param_2.getUserAgent();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
