package com.kayako.sdk.messenger.message;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class GetMessageListRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetMessageListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 30 branch to line 30
     * conditional line 31 branch to line 31
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_message_GetMessageListRequester_getHeaders_000_e9cd09c3673407e3() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            com.kayako.sdk.auth.FingerprintAuth param_0 = (com.kayako.sdk.auth.FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            Reflector.setField(param_0, "fingerprintId", null);
            String param_2 = "";
            GetMessageListRequester param_3 = (GetMessageListRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.GetMessageListRequester");
            Reflector.setField(param_3, "mQueryParameters", null);
            Reflector.setField(param_3, "mConversationId", null);
            Reflector.setField(param_3, "mFingerprintAuth", param_0);
            Reflector.setField(param_3, "mHelpDeskUrl", param_2);
            /* Act */
            retval = param_3.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Fingerprint-ID", null);
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_message_GetMessageListRequester_getHelpCenterUrl_000_c5735122d4f95ecf() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetMessageListRequester param_0 = (GetMessageListRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.GetMessageListRequester");
            Reflector.setField(param_0, "mQueryParameters", null);
            Reflector.setField(param_0, "mConversationId", null);
            Reflector.setField(param_0, "mFingerprintAuth", null);
            Reflector.setField(param_0, "mHelpDeskUrl", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
