package com.kayako.sdk.messenger.message;

import com.diffblue.deeptestutils.Reflector;
import com.kayako.sdk.auth.FingerprintAuth;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class GetMessageListRequesterTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: GetMessageListRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 30 branch to line 30
     * conditional line 31 branch to line 31
     */
    @Test
    public void init() throws Throwable {
        GetMessageListRequester instance;
        {
            /* Arrange */
            String param4 = "??????????";
            String helpdeskUrl = param4;
            FingerprintAuth fingerprintAuth = null;
            Long param1 = (Long) Reflector.getInstance("java.lang.Long");
            Reflector.setField(param1, "value", 0L);
            Long conversationId = param1;
            int offset = 7;
            int limit = 8;
            /* Act */
            /* Creating object to test constructor */
            instance = new GetMessageListRequester(helpdeskUrl, fingerprintAuth, conversationId, offset, limit);
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getHeaders() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            FingerprintAuth param0 = (FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            param0.setFingerprintId(null);
            String param2 = "";
            GetMessageListRequester param3 = (GetMessageListRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.GetMessageListRequester");
            Reflector.setField(param3, "mQueryParameters", null);
            Reflector.setField(param3, "mConversationId", null);
            Reflector.setField(param3, "mFingerprintAuth", param0);
            Reflector.setField(param3, "mHelpDeskUrl", param2);
            /* Act */
            retval = param3.getHeaders();
        }
        {
            /* Assert result */
            assertNotNull(retval);
            HashMap hashMap = new HashMap();
            hashMap.put("X-Fingerprint-ID", null);
            assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getHelpCenterUrl() throws Throwable {
        String retval;
        {
            /* Arrange */
            GetMessageListRequester param0 = (GetMessageListRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.GetMessageListRequester");
            Reflector.setField(param0, "mQueryParameters", null);
            Reflector.setField(param0, "mConversationId", null);
            Reflector.setField(param0, "mFingerprintAuth", null);
            Reflector.setField(param0, "mHelpDeskUrl", null);
            /* Act */
            retval = param0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void getQueryParameters() throws Throwable {
        Map<String, String> retval;
        {
            /* Arrange */
            String param1 = "";
            GetMessageListRequester param2 = (GetMessageListRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.GetMessageListRequester");
            Reflector.setField(param2, "mQueryParameters", null);
            Reflector.setField(param2, "mConversationId", null);
            Reflector.setField(param2, "mFingerprintAuth", null);
            Reflector.setField(param2, "mHelpDeskUrl", param1);
            /* Act */
            retval = param2.getQueryParameters();
        }
        {
            /* Assert result */
            assertEquals(null, retval);
        }
    }
}
