package com.kayako.sdk.messenger.message;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class MessageIncludeArgumentTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: MessageIncludeArgument */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 18 branch to line 19
     * conditional line 19 branch to line 19
     * conditional line 20 branch to line 20
     */
}
