package com.kayako.sdk.messenger.message;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class PutMessageRequesterTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: PutMessageRequester */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 31 branch to line 31
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_message_PutMessageRequester_getBodyParameters_000_f7d302d55eae5183() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            String param_1 = "";
            PutMessageRequester param_2 = (PutMessageRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.PutMessageRequester");
            Reflector.setField(param_2, "mBodyParams", null);
            Reflector.setField(param_2, "mConversationId", 0L);
            Reflector.setField(param_2, "mMessageId", 0L);
            Reflector.setField(param_2, "mHelpCenterUrl", param_1);
            Reflector.setField(param_2, "mFingerprintAuth", null);
            /* Act */
            retval = param_2.getBodyParameters();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_message_PutMessageRequester_getHeaders_000_25a8cebfcfcdfba1() throws Throwable {
        java.util.Map<String, String> retval;
        {
            /* Arrange */
            com.kayako.sdk.auth.FingerprintAuth param_0 = (com.kayako.sdk.auth.FingerprintAuth) Reflector.getInstance("com.kayako.sdk.auth.FingerprintAuth");
            Reflector.setField(param_0, "fingerprintId", null);
            String param_2 = "";
            PutMessageRequester param_3 = (PutMessageRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.PutMessageRequester");
            Reflector.setField(param_3, "mBodyParams", null);
            Reflector.setField(param_3, "mConversationId", 0L);
            Reflector.setField(param_3, "mMessageId", 0L);
            Reflector.setField(param_3, "mHelpCenterUrl", param_2);
            Reflector.setField(param_3, "mFingerprintAuth", param_0);
            /* Act */
            retval = param_3.getHeaders();
        }
        {
            /* Assert result */
            Assert.assertNotNull(retval);
            java.util.HashMap hashMap = new java.util.HashMap();
            hashMap.put("X-Fingerprint-ID", null);
            Assert.assertEquals(hashMap, retval);
        }
    }

    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_message_PutMessageRequester_getHelpCenterUrl_000_75b45d0aa3ae1f9() throws Throwable {
        String retval;
        {
            /* Arrange */
            PutMessageRequester param_0 = (PutMessageRequester) Reflector.getInstance("com.kayako.sdk.messenger.message.PutMessageRequester");
            Reflector.setField(param_0, "mBodyParams", null);
            Reflector.setField(param_0, "mConversationId", 0L);
            Reflector.setField(param_0, "mMessageId", 0L);
            Reflector.setField(param_0, "mHelpCenterUrl", null);
            Reflector.setField(param_0, "mFingerprintAuth", null);
            /* Act */
            retval = param_0.getHelpCenterUrl();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
