package com.kayako.sdk.messenger.message;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class PutMessageBodyParams_MessageStatusTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: PutMessageBodyParams_MessageStatus */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers:
     * conditional line 12 branch to line 15
     */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void com_kayako_sdk_messenger_message_PutMessageBodyParams_getMessageStatus_000_670eea6b5e46992c() throws Throwable {
        Object retval;
        {
            /* Arrange */
            PutMessageBodyParams param_0 = (PutMessageBodyParams) Reflector.getInstance("com.kayako.sdk.messenger.message.PutMessageBodyParams");
            Reflector.setField(param_0, "messageStatus", null);
            /* Act */
            retval = param_0.getMessageStatus();
        }
        {
            /* Assert result */
            Assert.assertEquals(null, retval);
        }
    }
}
