package com.kayako.sdk.messenger.conversation.fields;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import java.lang.reflect.Constructor;

public class ChannelTypeTest {

    @org.junit.Rule
    public ExpectedException thrown = ExpectedException.none();
    /* testedClasses: ChannelType */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
}
