package com.kayako.sdk.messenger.conversation.fields.priority;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.assertNotNull;

public class PriorityParserTest {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: PriorityParser */
    /*
     * Test generated by Diffblue Deeptest.
     * This test case covers the entire function.
     */
    @Test
    public void init() throws Throwable {
        PriorityParser instance;
        {
            /* Act */
            /* Creating object to test constructor */
            instance = new PriorityParser();
            assertNotNull(instance);
        /* Method return type is void, or not expected to return */
        }
    }
}
